path:
  ckpt_path: "./output/ckpt/selvas"
  log_path: "./output/log/selvas"
  result_path: "./output/result/selvas"
optimizer:
  batch_size: 4
  betas: [0.9, 0.98]
  eps: 0.000000001
  weight_decay: 0.0
  grad_clip_thresh: 1.0
  grad_acc_step: 1
  warm_up_step: 4000
  anneal_steps: [300000, 400000, 500000]
  anneal_rate: 0.3
  type: 'RAdam'  ##Adam, RAdam, null is SGD
scheduler:
  lr_step: 1 
  lr_decay_start: 10
step:
  total_step: 900000
  log_step: 100
  synth_step: 1000
  val_step: 1000
  save_step: 100000
